name: Build and Test JavaScript Functions

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x] # Test on multiple Node versions
    timeout-minutes: 30 # Increase timeout for the job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache-dependency-path: package-lock.json
          always-auth: false
          check-latest: true # Ensure using the latest version of the action
      
      - name: Install dependencies
        run: npm install
      
      - name: Run tests
        run: npm test # Assuming you have Jest, Mocha, or another test framework set up
